language: go
go:
  - 1.11.x

script:
  - make fmt
  - make test

notifications:
  email:
    on_success: never
    on_failure: always

before_deploy:
  - make release

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: C4YAeSLcq3wVX7tE37NHRRzYHZitwD/3DIRX1L6oLFwe00c/1xKa9iiTD3Gdzv13NjF2f+B6yC2W8XVO/QcPdkJ7LEftlA8JZDJnrUBgSPNNOit2M9hMIoKV1XcKXFV3TNlHVYQGQ1wGTeQXH0VeLaNRfRhlyf8kA4qpHys/KxC2bjyd+zzGyf2w6DrFzx+ydruWdy3kGy/hXWlWMWqSsrhrRoEVTokVOM9nug6oB/geoVx0JcWemhOnoZjalxMpKSKRw595QHOZCuBpsfOeUOGAQxeI4fBE7kakEIXEnrBQEKRAukhm2T2K+7neS44cySnYrmAgpLwY88G5F31h2MsVWu/E5sIXu83j+NWKGlGtWRE0PVKo7wBTmICTqtkKhSn8mJk3F96rMs4GU7KZ17nIbZdnCHddz2VPrlLeNFB464lwnqfSh0Je9Kq5uAQPtVbRX/aas0AqGlRWHbHEBcBfjpGL6hMpSO5tRvTyXtz4n6yiS712ah7tYik/uKesJJkIEDwkb2ys53pWsTA2oyXqtV6cCXcLCYE05gCfTT8spV9BkTSM2X9nUAu/i+/D8qOzdvlxNGca55FKeuBRkex2soycjj1Fetu1R6VqWO/D016oV7PZ+uMX5xtABvyEIZAqGwZlERXkI4PgLNsB7iUpO0prH7aoITXQU1SxRVo=
  file:
    - bin/retry-mac
    - bin/retry-linux
    - bin/retry.exe
  on:
    repo: martinezdelariva/retry
    tags: true
