language: go

go:
  - 1.11.x
script:
  - make fmt
  - make test

notifications:
  email:
    on_success: never
    on_failure: always

before_deploy:
  - make release

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: RLaO3l4XIAHdw+38XLkQ1LqvJscCJKkAahB3YSY/MUXS7Mr9q+AGjUyPISTG5gRxA7xdRc1qDgVzhVzRWek7xTKJOpY2MP3BU2mCwGZcZrg9a9VdKTyuAhXGzVRR3Rjb+wIkyYzC2Zuf/XRvQmPWhbjTahnCbW0sA4KAlvh1GPzoWoSqCLewrpmz5FV4eau5M3IizOi3AFZ5kvGAoLkgI2d0N2oLyYx9Wv7poiW0WJeWGGRaFM57fCYcocvKFcEJ7iaQB7sqsnl/V27FzmxBQsCOlEi9YkONVA+cgLUm6dLTHXvnMlEWkO5p6Z7TQK2O4+T60rjjgbkRo/PNp2sxS+hMtYp2WvBBkSFZN9E0HiWvlLv7oaLiWxi5BoK8ExBY36PHbbeMEyRluxW13C8kOPn95b1Y0vCXfol0geoo5dOBU+Jy1XP6NzU61FHt/ied0VGH5XxbnxgT1S+a5qvLVfwTWRoSCiHvl75JlOp7LmXfimGfEuxQFyhnTluW70tDa8YEpGADETC2qV44rSXZiMmPjlqT3ETgA8zvoKKv+uBy/rUdBVlqF7tOmBhSy5Hw+SEa5YlXbu2u/n87Q0zLG7NIke2uYN9EHaM9iWC24Yj20q2mrHhQAGcx9ng42klMuJB15uFhzNPpCeMChYjerwu20ssga3UB+MXsT87A8zU=
  file:
    - bin/retry-mac
    - bin/retry-linux
    - bin/retry.exe
  on:
    repo: martinezdelariva/retry
    tags: true
