language: go
go:
- 1.11.x
script:
- make fmt
- make test
notifications:
  email:
    on_success: never
    on_failure: always
before_deploy:
- make release
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: M+F/pwayTWBXY8AEr3dMn5rZWHvoslf8Gr2JMwi0TF71/nPmzTga4dI+SICvI9Sjdc5vXvaTAlJF+YnepigsxwGTc/mq7Yvpz7cpkMVUWXiy1e2Xidcy40undlbdK5WPoChud8HZEDxvXqS+dPCr0jzOK9ODIqdu0/PbBG6Uh9YLIPAamFaQHfPHZFhE1QqPGfYOZVbOCD2KmGFumUmwIrIGWhKfwzjNIpxkMdk+X6tysVjDzxzGG5jXsziV9qlSGguLtbPRWDsKgif7BNu1b1u243NjJwWb9N10H3jy2JHlmxjPpJK4LUo48s8CYiQGtrh6nxJIxmf3oxF200BVY8Ggp7BRCztcRB60yQeyvbjW9jl/bxkG/MgE2nZd8C7Y8PomlqSsOfrlicyh2C/sf6JKjrH/0bSUAMFETe4Ogk89eNOMSbVEb+zRSTpTEhRKGsd7lIc9cdtvd60r/GwLaiOwAbG3yMYQM5/ZQqm8clsx/6NzeW8VsUIkKHczMsXoGsqCUY9hRzdC7qJyXXu3U3HyA6rXElrYomdrW+nOrnAabndvGTG7aYRZLwt6OGvL+Gtg7c0uVx1+8IOIet08Iw1nkJ1HzhlToG86YQe8tyuVFsdshZBZXZrLYWmnMKzJBZbfqRvdsz8QqSVOOerODN4dgGxadP57e0EKltlr8/c=
  file: bin/retry-mac
  on:
    repo: martinezdelariva/retry
    tags: true
