language: go

go:
  - 1.11.x
script:
  - make fmt
  - make test

notifications:
  email:
    on_success: never
    on_failure: always

before_deploy:
  - make release

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: OubzW3+pK2HRPknOUgMG2GuDRiwm+MTiOZi8y6afIC0GTERUvRFVG4SMF+4M9hD/l/WNGqUCTgnM4q9otOTe62Ome6sRUwP6iF1VDPs4KxLn4nKM8sJS4aleulbmFdrWZ73Z0GAvz1uJnsiUbz8dJVEk0dSuXVEk1mmwFaSzfc6gvhrOUwz/KBObu4tdj6/IYwT02lwJdc/gz1/C3guk3piH7ihzz8acv7gZpzgYO8sXfu0t/io2CQ0DhBpijOP7yGEVGJfnCtPp06Oq0De+b/KI7g7RVs0XETdErr+htu1kD7dPZq2C3vVqxW4LAHXGWHeRfYGxQtIbDaZNy14vOkv0IaaD1P75kgaSbf7xi30uDnSs16+UKOIMC9df22OFcSN7rhRWKleep+96zeWGHnm9XLnVsauPZb+HUcfYz2XqzJ6sll/zNkHLLiejg4q5duqxtLYD9xEsOP0vpat6j9r4k630j3BuTuH5bdHsWaSiyu1t+4DKtVyt+EuogkUYdXB1hlZVzFxO2XCUcv0r4xyMjiro1dfssHi5nYyEGlu3QF9Ghv4V8oH6sO6KKZQcx8IoYbBYAS4MDOYFozmK0XFDiG2zrq7lNh8wPTejD4iHZvG1xrmEl9x4G+9IPc+bpdlvq/L4AzASR503MjycX6EIwPEj9zEhfUWmd3sGbFg=
  file: bin/retry-mac
  on:
    repo: martinezdelariva/retry
    tags: true
