language: go

go:
  - 1.11.x
script:
  - make fmt
  - make test

notifications:
  email:
    on_success: never
    on_failure: always

before_deploy:
  - make release

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: c9cMWroUxbArhdYvPWUO2OxuU/VkkqZzZxwmomYqREk7wHuges0HVBDJYRzDR8YlbT7iDlMtI+lcoHcntqlsRV2KSd7kbwxE8UGSIfesThLHBoVWbFGQmDXXhYTPNxkhQq0Q8Ceo/yL9Z+QUrNbxoTfSGYkvIObQxWMLSgQ82ld92VXMjcytiFQkoz0FKzyad1qfdm3L3GLLqdyjY1GCV9lF5/U+rFF/Yh4+9ocGyxzhOvjshO0bzvWsBkQpnsKxqYRIeuizAJ5+EKyI7k2XovLD6mOHMqEeu1klodyb48oott+WWvZqwreo1VnTFu1bY6X0Y01PhHXHzo5dsyaMHq1/CRh4BQuTfv5ILYXFTqW8B0P+0a/O99GLZY0z+6r+152Ee4K90pl7NDplz2O1A7EdB8Ja8zcqXi50mzvQLNPr3q1ZZfMryxjvJHBpW2n6QJbsKOtB3s/Gcguc+oX2dLe0djse0ulEVZxhwgYhN5+2XCLkRtf3/dnoKXm/yyd7I2lwoCBLVeKk8Y9sbMdBZLtvIOKA3T32E5LhujKxhnUiauN3PzqMRI9rDzxx9twr7tWzqzKBK89vVHAVUH06XCPO57R6oNYAtHGuG7SCJvnEcdwwaRZh2DUi4QMYRj91CgqLUmYU7BOvhxaLulZvtC+0QlfdlwFEeB/hgoybAiw=
  file:
    - bin/retry-linux
    - bin/retry-mac
    - bin/retry.exe
  on:
    repo: martinezdelariva/retry
    tags: true
